#cloud-config

runcmd:
  - echo "Hello from Terraform!" > /etc/motd
users:
  - default
  - name: test
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ${public_key}

chpasswd:
  expire: false

ssh_pwauth: false
